export type FormPriority = 'critical' | 'important' | 'refinement';

export interface FormCheck {
  id: string;
  question: string;
  priority: FormPriority;
  cue?: string;
}

export const FORM_CHECKS: Record<string, FormCheck[]> = {
  'Shadow Push': [
    { id: 'elbow_angle', question: 'Elbows at 45° to torso?', priority: 'critical', cue: 'Flare less, protect shoulders' },
    { id: 'bar_to_chest', question: 'Bar touches mid-chest?', priority: 'critical', cue: 'Full ROM is non-negotiable' },
    { id: 'wrists_straight', question: 'Wrists straight, not bent back?', priority: 'important', cue: 'Keep wrists neutral' },
    { id: 'feet_planted', question: 'Feet flat on floor?', priority: 'important', cue: 'Stable base = stable press' },
    { id: 'scapula_retracted', question: 'Shoulder blades retracted before descent?', priority: 'refinement', cue: 'Pack shoulders for power' },
    { id: 'breathing', question: 'Exhaling on the press?', priority: 'important', cue: 'Breathe properly for core stability' },
  ],
  'Samurai Row': [
    { id: 'back_flat', question: 'Back flat, not rounded?', priority: 'critical', cue: 'Neutral spine prevents injury' },
    { id: 'elbows_drive', question: 'Elbows driving past ribcage?', priority: 'critical', cue: 'Pull long, not high' },
    { id: 'scapula_squeeze', question: 'Shoulder blades squeezed at top?', priority: 'important', cue: 'Squeeze for 1 count' },
    { id: 'full_extension', question: 'Arms fully extended each rep?', priority: 'important', cue: 'Stretch at bottom for full ROM' },
    { id: 'no_hips_rise', question: 'Hips staying down, not rising?', priority: 'refinement', cue: 'Stable hips = better lat activation' },
  ],
  'Iron Squat': [
    { id: 'back_straight', question: 'Back straight, chest up?', priority: 'critical', cue: 'Neutral spine is priority one' },
    { id: 'depth', question: 'Thighs below parallel?', priority: 'critical', cue: 'Depth builds glutes and mobility' },
    { id: 'knees_tracking', question: 'Knees tracking over toes?', priority: 'critical', cue: 'Don\'t let knees cave in' },
    { id: 'heels_down', question: 'Heels on ground throughout?', priority: 'important', cue: 'Weight through midfoot' },
    { id: 'hip_break', question: 'Breaking at hips first, not knees?', priority: 'important', cue: 'Hip hinge initiates the squat' },
    { id: 'core_braced', question: 'Core braced throughout?', priority: 'refinement', cue: 'Big breath, brace, descend' },
  ],
  'Crimson Press': [
    { id: 'core_braced', question: 'Core braced, not arching back?', priority: 'critical', cue: 'Don\'t sacrifice spine for weight' },
    { id: 'full_lockout', question: 'Arms fully extended overhead?', priority: 'important', cue: 'Lockout at top' },
    { id: 'bar_path', question: 'Bar path straight, not wobbling?', priority: 'important', cue: 'Vertical bar path' },
    { id: 'elbows_front', question: 'Elbows slightly in front of bar?', priority: 'critical', cue: 'Elbows under bar at bottom' },
    { id: 'shoulders_down', question: 'Shoulders down, not shrugged?', priority: 'refinement', cue: 'Depress scapula' },
  ],
  'Steel Deadlift': [
    { id: 'neutral_spine', question: 'Spine neutral, not rounded?', priority: 'critical', cue: 'Belt of armor: keep it straight' },
    { id: 'hips_drop', question: 'Hips dropped, not too high?', priority: 'critical', cue: 'Low hips = strong pull' },
    { id: 'bar_contact', question: 'Bar against shins throughout?', priority: 'important', cue: 'Drag the bar up your legs' },
    { id: 'hip_thrust', question: 'Hips thrust forward at lockout?', priority: 'important', cue: 'Finish with glutes' },
    { id: 'shoulders_over_bar', question: 'Shoulders over bar at start?', priority: 'critical', cue: 'Start position determines everything' },
    { id: 'brace_before_pull', question: 'Bracing core before pulling?', priority: 'refinement', cue: 'Pull the slack first' },
  ],
  'Core Strike': [
    { id: 'neck_neutral', question: 'Neck neutral, not pulling?', priority: 'critical', cue: 'Look at ceiling, not knees' },
    { id: 'controlled_descent', question: 'Lowering under control?', priority: 'important', cue: 'Eccentric is half the work' },
    { id: 'full_crunch', question: 'Full contraction at the top?', priority: 'important', cue: 'Squeeze at peak' },
    { id: 'feet_down', question: 'Feet staying on ground?', priority: 'refinement', cue: 'Stable feet = core focus' },
    { id: 'exhale_on_effort', question: 'Exhaling on the curl-up?', priority: 'refinement', cue: 'Never hold your breath' },
  ],
  'Blade Curl': [
    { id: 'elbows_pinned', question: 'Elbows pinned to ribs?', priority: 'critical', cue: 'Elbows don\'t travel forward' },
    { id: 'no_swing', question: 'No body swing for momentum?', priority: 'critical', cue: 'Strict form builds peak' },
    { id: 'full_range', question: 'Full extension at bottom?', priority: 'important', cue: 'Stretch then contract' },
    { id: 'wrist_straight', question: 'Wrists straight, not curling?', priority: 'important', cue: 'Neutral wrist = bicep focus' },
    { id: 'slow_lower', question: 'Lowering phase slower than lifting?', priority: 'refinement', cue: '2s down, 1s up' },
  ],
  'Dojo Dip': [
    { id: 'torso_lean', question: 'Torso leaning slightly forward?', priority: 'important', cue: 'Forward lean targets chest' },
    { id: 'depth_90', question: 'Upper arms parallel to floor?', priority: 'critical', cue: 'Go deep enough' },
    { id: 'no_shrug', question: 'Shoulders down, not shrugged?', priority: 'critical', cue: 'Keep shoulders packed' },
    { id: 'controlled', question: 'Controlled descent, not dropping?', priority: 'important', cue: '3s down, explode up' },
  ],
  'Ronin Lunge': [
    { id: 'front_shin', question: 'Front shin vertical, not past toes?', priority: 'critical', cue: 'Shin angle protects knees' },
    { id: 'back_knee', question: 'Back knee almost touching floor?', priority: 'important', cue: 'Full range for glute activation' },
    { id: 'torso_upright', question: 'Torso upright, not leaning?', priority: 'critical', cue: 'Chest tall, shoulders back' },
    { id: 'drive_heel', question: 'Driving through front heel?', priority: 'important', cue: 'Push the world away' },
    { id: 'step_length', question: 'Step length appropriate (not too short)?', priority: 'refinement', cue: 'Long enough for 90/90' },
  ],
  'Warrior Pull-up': [
    { id: 'full_hang', question: 'Full hang at bottom, arms straight?', priority: 'critical', cue: 'Dead hang builds lat stretch' },
    { id: 'chest_to_bar', question: 'Chest pulled to bar?', priority: 'critical', cue: 'More than chin over bar' },
    { id: 'no_kip', question: 'No kipping or swinging?', priority: 'important', cue: 'Strict = maximum gain' },
    { id: 'elbows_down', question: 'Elbows driving down and back?', priority: 'important', cue: 'Pull elbows to pockets' },
    { id: 'scapular_start', question: 'Scapula retracted before pulling?', priority: 'refinement', cue: 'Initiate with shoulders' },
  ],
  'Oni Press': [
    { id: 'control_descent', question: 'Dumbbells controlled on descent?', priority: 'important', cue: '2s down' },
    { id: 'arc_path', question: 'Arc path, not straight up?', priority: 'critical', cue: 'Hugging a tree motion' },
    { id: 'squeeze_top', question: 'Squeezing chest at top?', priority: 'important', cue: 'Mind-muscle connection' },
    { id: 'even_press', question: 'Both arms pressing evenly?', priority: 'critical', cue: 'Don\'t let one side cheat' },
    { id: 'palms_forward', question: 'Palms facing forward at top?', priority: 'refinement', cue: 'Shoulder-safe rotation' },
  ],
  'Shield Raise': [
    { id: 'no_swing', question: 'No body swing for momentum?', priority: 'critical', cue: 'Momentum kills the gain' },
    { id: 'elbows_lead', question: 'Leading with elbows, not hands?', priority: 'critical', cue: 'Think "elbows to ceiling"' },
    { id: 'shoulder_height', question: 'Arms raised to shoulder height?', priority: 'important', cue: 'Parallel to floor' },
    { id: 'controlled_lower', question: 'Lowering under control?', priority: 'important', cue: 'Fight the descent' },
    { id: 'thumbs_up', question: 'Thumbs pointing up throughout?', priority: 'refinement', cue: 'Shoulder-safe rotation' },
  ],
  'Thunder Slam': [
    { id: 'full_extension', question: 'Full overhead extension?', priority: 'critical', cue: 'Reach high for max power' },
    { id: 'hip_hinge', question: 'Hinging at hips, not squatting?', priority: 'critical', cue: 'Hinge loads the posterior chain' },
    { id: 'explosive', question: 'Explosive slam?', priority: 'important', cue: 'Power is the purpose' },
    { id: 'catch_low', question: 'Catching ball in low stance?', priority: 'important', cue: 'Stay athletic' },
    { id: 'core_braced', question: 'Core braced at impact?', priority: 'refinement', cue: 'Protect the spine' },
  ],
  'Silent Plank': [
    { id: 'straight_line', question: 'Body in straight line, no sag?', priority: 'critical', cue: 'Hips at neutral' },
    { id: 'elbows_under', question: 'Elbows directly under shoulders?', priority: 'critical', cue: '90° at the elbow' },
    { id: 'glutes_engaged', question: 'Glutes squeezed?', priority: 'important', cue: 'Activate posterior chain' },
    { id: 'steady_breath', question: 'Breathing steady, not holding?', priority: 'important', cue: 'Breathe through the hold' },
    { id: 'neck_neutral', question: 'Neck neutral, gaze down?', priority: 'refinement', cue: 'Cervical spine alignment' },
  ],
  'Dragon Squat': [
    { id: 'knees_out', question: 'Knees pushing outward?', priority: 'critical', cue: 'Knees out = hip stability' },
    { id: 'torso_upright', question: 'Torso staying upright?', priority: 'critical', cue: 'Upright torso for quad focus' },
    { id: 'depth', question: 'Hips below knees?', priority: 'important', cue: 'ATG for full development' },
    { id: 'heels_down', question: 'Heels on ground?', priority: 'important', cue: 'Ankle mobility check' },
    { id: 'tempo_control', question: 'Controlled descent, not dive-bombing?', priority: 'refinement', cue: '3s down, explode up' },
  ],
  'Shadow Sprint': [
    { id: 'high_knees', question: 'Knees driving to hip height?', priority: 'critical', cue: 'Drive knees high' },
    { id: 'arms_pumping', question: 'Arms pumping opposite legs?', priority: 'important', cue: 'Arm-leg coordination' },
    { id: 'light_feet', question: 'Landing light on feet?', priority: 'important', cue: 'Quiet feet = efficient' },
    { id: 'core_braced', question: 'Core braced, not slouching?', priority: 'important', cue: 'Posture under speed' },
    { id: 'rhythm', question: 'Steady rhythm maintained?', priority: 'refinement', cue: 'Find your cadence' },
  ],
  'Iron Grip': [
    { id: 'arms_straight', question: 'Arms straight throughout?', priority: 'critical', cue: 'Locked arms isolate forearms' },
    { id: 'finger_roll', question: 'Rolling with fingers, not wrists?', priority: 'critical', cue: 'Finger flexion builds grip' },
    { id: 'full_squeeze', question: 'Full squeeze at top?', priority: 'important', cue: 'Crush at peak' },
    { id: 'controlled_unroll', question: 'Controlled unroll, not dropping?', priority: 'important', cue: 'Eccentric finger training' },
  ],
  'Kensei Cut': [
    { id: 'back_flat', question: 'Back flat, bench supporting?', priority: 'critical', cue: 'Bench must support your back' },
    { id: 'elbow_high', question: 'Elbow driving high, not wide?', priority: 'critical', cue: 'High elbow = lat focus' },
    { id: 'lat_squeeze', question: 'Lat squeezed at peak?', priority: 'important', cue: 'Squeeze the armpit' },
    { id: 'full_stretch', question: 'Full stretch at bottom?', priority: 'important', cue: 'Stretch the lat at bottom' },
    { id: 'palm_forward', question: 'Palm facing forward?', priority: 'refinement', cue: 'Pronated grip targets lats' },
  ],
  'Stone Lift': [
    { id: 'heels_down', question: 'Heels pressing into floor?', priority: 'critical', cue: 'Heels planted = max power' },
    { id: 'hips_full', question: 'Hips fully extended at top?', priority: 'critical', cue: 'Full hip extension' },
    { id: 'glute_squeeze', question: 'Glutes squeezed hard at peak?', priority: 'important', cue: 'Squeeze for 2s' },
    { id: 'controlled_lower', question: 'Lowering under control, not dropping?', priority: 'important', cue: 'Fight the negative' },
    { id: 'ribs_down', question: 'Ribs down, not flaring?', priority: 'refinement', cue: 'Protect the lower back' },
  ],
  'Wind Strike': [
    { id: 'limbs_straight', question: 'Arms and legs straight?', priority: 'critical', cue: 'Aim for total extension' },
    { id: 'simultaneous', question: 'Lifting simultaneously, not staggered?', priority: 'critical', cue: 'Sync your limbs' },
    { id: 'peak_pause', question: 'Pausing at peak contraction?', priority: 'important', cue: 'Hold at the top' },
    { id: 'controlled_lower', question: 'Lowering under control, keeping off floor?', priority: 'important', cue: 'Control the descent' },
    { id: 'breathing', question: 'Exhaling at the peak?', priority: 'refinement', cue: 'Don\'t hold your breath' },
  ],
  // New 21-40 form checks
  'Iron Push': [
    { id: 'diamond_hands', question: 'Hands forming diamond under chest?', priority: 'critical', cue: 'Thumbs and index fingers touch' },
    { id: 'elbows_tucked', question: 'Elbows close to body, not flared?', priority: 'critical', cue: 'Tucked elbow targets triceps' },
    { id: 'depth_near_floor', question: 'Chest stopping just above hands?', priority: 'important', cue: 'Full ROM for pectoral stretch' },
    { id: 'straight_line', question: 'Body in straight plank, no sag?', priority: 'important', cue: 'Glutes and core engaged' },
    { id: 'explosive_up', question: 'Exploding up, not grinding?', priority: 'refinement', cue: 'Power on the concentric' },
  ],
  'Rise Guard': [
    { id: 'no_momentum', question: 'No body sway for momentum?', priority: 'critical', cue: 'Strict form or no gain' },
    { id: 'lead_elbows', question: 'Leading movement with elbows?', priority: 'critical', cue: 'Elbows high = delt activation' },
    { id: 'shoulder_height', question: 'Weights at shoulder height?', priority: 'important', cue: 'Parallel to floor' },
    { id: 'tilt_forward', question: 'Slight forward tilt at top?', priority: 'important', cue: 'Target the lateral delt' },
    { id: 'controlled_lower', question: 'Lowering slowly, not dropping?', priority: 'refinement', cue: '3s eccentric for burn' },
  ],
  'Skull Break': [
    { id: 'upper_arms_vertical', question: 'Upper arms staying vertical?', priority: 'critical', cue: 'Stationary upper arms = triceps work' },
    { id: 'lower_to_forehead', question: 'Weight lowering to forehead, not chest?', priority: 'critical', cue: 'Forehead target safe for elbows' },
    { id: 'full_lockout', question: 'Full extension at top?', priority: 'important', cue: 'Lockout for full contraction' },
    { id: 'elbows_in', question: 'Elbows pointing to ceiling, not flaring?', priority: 'important', cue: 'Elbows neutral = joint safety' },
    { id: 'slow_negative', question: 'Controlled descent, not bouncing?', priority: 'refinement', cue: '2s down, 1s up' },
  ],
  'Mountain Press': [
    { id: 'bench_angle', question: 'Bench at 45° incline?', priority: 'important', cue: 'Angle targets upper chest' },
    { id: 'arc_motion', question: 'Arc-shaped press path?', priority: 'critical', cue: 'Slight arc, not straight up' },
    { id: 'squeeze_top', question: 'Squeezing at the top?', priority: 'important', cue: 'Mind-muscle connection' },
    { id: 'control_descent', question: 'Dumbbells controlled on descent?', priority: 'important', cue: 'Stop at shoulder level' },
    { id: 'scapula_packed', question: 'Shoulder blades packed into bench?', priority: 'refinement', cue: 'Stable base for heavy press' },
  ],
  'Iron Draw': [
    { id: 'flat_back', question: 'Back flat, chest open?', priority: 'critical', cue: 'Hinge position never rounds' },
    { id: 'bar_to_sternum', question: 'Bar pulled to sternum?', priority: 'critical', cue: 'Sternum touch = full row' },
    { id: 'elbows_past', question: 'Elbows driving past torso?', priority: 'critical', cue: 'Elbows behind back at peak' },
    { id: 'mid_back_squeeze', question: 'Mid-back squeezed at peak?', priority: 'important', cue: 'Squeeze for 2 count' },
    { id: 'full_extension', question: 'Arms fully extended each rep?', priority: 'important', cue: 'Stretch at bottom' },
    { id: 'no_hips_rise', question: 'Hips not rising as you pull?', priority: 'refinement', cue: 'Stable hinge position' },
  ],
  'Steel Curl': [
    { id: 'elbows_pinned', question: 'Elbows pinned to ribs?', priority: 'critical', cue: 'Elbows don\'t travel' },
    { id: 'no_swing', question: 'No back swing for momentum?', priority: 'critical', cue: 'Strict = bigger peaks' },
    { id: 'full_extension', question: 'Full extension at bottom?', priority: 'important', cue: 'Never stop short' },
    { id: 'wrist_neutral', question: 'Wrists neutral, not curling?', priority: 'important', cue: 'Straight wrists = bicep focus' },
    { id: 'squeeze_and_lower', question: 'Squeezing at top, slow descent?', priority: 'refinement', cue: '3s eccentric for growth' },
  ],
  'Mask Pull': [
    { id: 'hands_separate', question: 'Hand separating at face?', priority: 'critical', cue: 'Pull hands apart at end range' },
    { id: 'face_height', question: 'Band at face height, not chest?', priority: 'critical', cue: 'Face height targets rear delts' },
    { id: 'external_rotation', question: 'Externally rotating at peak?', priority: 'important', cue: 'Rotate palms slightly up' },
    { id: 'full_extension', question: 'Full release without slack?', priority: 'important', cue: 'Keep tension in the band' },
    { id: 'scapula_retract', question: 'Scapula retracted throughout?', priority: 'refinement', cue: 'Shoulders back and down' },
  ],
  'Reverse Row': [
    { id: 'straight_plank', question: 'Body in straight plank, no sag?', priority: 'critical', cue: 'Hips aligned with shoulders' },
    { id: 'chest_to_bar', question: 'Chest touching the bar?', priority: 'critical', cue: 'Full range pull' },
    { id: 'full_hang', question: 'Full hang at bottom, arms straight?', priority: 'important', cue: 'Lat stretch at the bottom' },
    { id: 'elbows_45', question: 'Elbows at 45° to torso?', priority: 'important', cue: 'Not flared, not tucked' },
    { id: 'core_braced', question: 'Core braced, hips stable?', priority: 'refinement', cue: 'Brace like a plank' },
  ],
  'Eastern Hinge': [
    { id: 'bar_along_thighs', question: 'Bar traveling along thighs?', priority: 'critical', cue: 'Bar stays in contact' },
    { id: 'flat_back', question: 'Flat back, not rounding?', priority: 'critical', cue: 'Neutral spine protects lower back' },
    { id: 'soft_knees', question: 'Knees soft, not locked?', priority: 'important', cue: 'Slight bend throughout' },
    { id: 'deep_stretch', question: 'Feeling deep hamstring stretch?', priority: 'important', cue: 'Go to limit of mobility' },
    { id: 'hip_drive', question: 'Driving hips forward to stand?', priority: 'critical', cue: 'Hips initiate the return' },
    { id: 'glute_squeeze', question: 'Glutes squeezed at lockout?', priority: 'refinement', cue: 'Finish with glutes' },
  ],
  'Split Squat': [
    { id: 'front_shin_vertical', question: 'Front shin vertical, not past toes?', priority: 'critical', cue: 'Protect the front knee' },
    { id: 'back_knee_touch', question: 'Back knee nearly touching floor?', priority: 'critical', cue: 'Full range for glute activation' },
    { id: 'torso_upright', question: 'Torso upright, not leaning forward?', priority: 'important', cue: 'Tall chest throughout' },
    { id: 'heel_drive', question: 'Driving through front heel?', priority: 'important', cue: 'Heel power = glutes' },
    { id: 'hip_square', question: 'Hips square, not rotating?', priority: 'refinement', cue: 'Hips face forward' },
  ],
  'Rising Calf': [
    { id: 'full_stretch', question: 'Heels dropping below edge?', priority: 'critical', cue: 'Stretch at bottom for full ROM' },
    { id: 'full_rise', question: 'Rising to full tip-toe?', priority: 'critical', cue: 'Max height for peak contraction' },
    { id: 'pause_top', question: 'Pausing at top for 2 seconds?', priority: 'important', cue: 'Isometric at peak' },
    { id: 'knees_straight', question: 'Knees straight, not bent?', priority: 'important', cue: 'Straight legs isolate gastrocnemius' },
    { id: 'slow_lower', question: 'Lowering slowly, not dropping?', priority: 'refinement', cue: '3s eccentric for growth' },
  ],
  'Warrior March': [
    { id: 'upright_torso', question: 'Torso upright throughout?', priority: 'critical', cue: 'Don\'t lean forward' },
    { id: 'knee_tracking', question: 'Front knee tracking over toes?', priority: 'critical', cue: 'Knee never caves inward' },
    { id: 'stride_length', question: 'Stride long enough for 90° angle?', priority: 'important', cue: 'Not too short, not too long' },
    { id: 'continuous_flow', question: 'Continuous walking, not stopping?', priority: 'important', cue: 'March with purpose' },
    { id: 'heel_toe', question: 'Leading with heel, landing flat?', priority: 'refinement', cue: 'Heel strike then absorb' },
  ],
  'Dawn Reach': [
    { id: 'hips_back', question: 'Pushing hips back on descent?', priority: 'critical', cue: 'Hips initiate the hinge' },
    { id: 'flat_back', question: 'Back flat, not rounded?', priority: 'critical', cue: 'Neutral spine throughout' },
    { id: 'gaze_forward', question: 'Gaze forward, not down?', priority: 'important', cue: 'Neck alignment follows spine' },
    { id: 'torso_parallel', question: 'Torso parallel to floor at bottom?', priority: 'important', cue: 'Full hinge depth' },
    { id: 'hip_drive', question: 'Driving hips forward on return?', priority: 'critical', cue: 'Hip thrust completes the lift' },
    { id: 'knee_soft', question: 'Knees staying soft, not locked?', priority: 'refinement', cue: 'Slight bend throughout' },
  ],
  'Hanging Rise': [
    { id: 'no_swing', question: 'No swinging or kipping?', priority: 'critical', cue: 'Strict = core work' },
    { id: 'legs_straight', question: 'Legs straight, not bent?', priority: 'critical', cue: 'Straight legs = lower abs' },
    { id: 'parallel_floor', question: 'Legs parallel to floor at top?', priority: 'important', cue: 'Parallel is the standard' },
    { id: 'full_hang', question: 'Full hang at bottom, shoulders engaged?', priority: 'important', cue: 'Active shoulder at bottom' },
    { id: 'controlled_lower', question: 'Lowering under control?', priority: 'refinement', cue: '3s descent' },
  ],
  'Wheel Strike': [
    { id: 'hips_stable', question: 'Hips not sagging or rising?', priority: 'critical', cue: 'Plank position throughout' },
    { id: 'full_extension', question: 'Body fully extended at peak?', priority: 'critical', cue: 'Arms overhead, body straight' },
    { id: 'core_pull', question: 'Pulling back with abs, not arms?', priority: 'critical', cue: 'Ab strength returns you' },
    { id: 'kneel_stable', question: 'Knees stable on floor?', priority: 'important', cue: 'Padding for comfort' },
    { id: 'controlled_roll', question: 'Controlled roll out and in?', priority: 'refinement', cue: 'Speed kills form' },
  ],
  'Side Guard': [
    { id: 'elbow_under', question: 'Elbow directly under shoulder?', priority: 'critical', cue: '90° alignment at shoulder' },
    { id: 'straight_line', question: 'Body in straight line?', priority: 'critical', cue: 'No sag, no pike' },
    { id: 'hips_high', question: 'Hips lifted high enough?', priority: 'important', cue: 'Don\'t let hips drop' },
    { id: 'core_braced', question: 'Core braced, obliques engaged?', priority: 'important', cue: 'Crunch toward the floor' },
    { id: 'feet_stacked', question: 'Feet stacked, not staggered?', priority: 'refinement', cue: 'Top foot slightly ahead' },
    { id: 'steady_breath', question: 'Breathing steadily through hold?', priority: 'refinement', cue: 'Don\'t hold breath' },
  ],
  'Kettle Storm': [
    { id: 'hip_drive', question: 'Explosive hip drive, not arms lifting?', priority: 'critical', cue: 'Hips power the swing' },
    { id: 'flat_back', question: 'Back flat on the hinge?', priority: 'critical', cue: 'Neutral spine throughout' },
    { id: 'bell_chest_height', question: 'Kettlebell floating to chest height?', priority: 'important', cue: 'Shoulder height max' },
    { id: 'arms_relaxed', question: 'Arms relaxed, not pulling?', priority: 'important', cue: 'Let the bell float' },
    { id: 'core_braced', question: 'Core braced on every rep?', priority: 'refinement', cue: 'Brace before each swing' },
    { id: 'full_hip_extension', question: 'Full hip extension at the top?', priority: 'critical', cue: 'Stand tall and squeeze' },
  ],
  'Leap of Faith': [
    { id: 'full_extension', question: 'Full hip extension on jump?', priority: 'critical', cue: 'Stand tall before landing' },
    { id: 'soft_landing', question: 'Soft landing, not stomping?', priority: 'critical', cue: 'Absorb like a ninja' },
    { id: 'both_feet', question: 'Both feet landing simultaneously?', priority: 'critical', cue: 'Even landing distribution' },
    { id: 'arms_drive', question: 'Arms driving upward to assist?', priority: 'important', cue: 'Arm swing adds height' },
    { id: 'safe_landing', question: 'Stepping down, not jumping down?', priority: 'important', cue: 'Step off safely' },
    { id: 'box_height', question: 'Box height appropriate for ability?', priority: 'refinement', cue: 'Don\'t ego lift on box height' },
  ],
  'Mountain Storm': [
    { id: 'low_hips', question: 'Hips staying low, not rising?', priority: 'critical', cue: 'Plank position maintained' },
    { id: 'core_braced', question: 'Core braced throughout?', priority: 'critical', cue: 'Don\'t let back arch' },
    { id: 'full_range', question: 'Knee driving fully to chest?', priority: 'important', cue: 'Full knee drive each rep' },
    { id: 'rhythm', question: 'Steady rhythm maintained?', priority: 'important', cue: 'Find your cadence' },
    { id: 'breathing', question: 'Breathing steady, not gasping?', priority: 'refinement', cue: 'Nose in, mouth out' },
  ],
  'Rope Dance': [
    { id: 'soft_landing', question: 'Landing softly on balls of feet?', priority: 'critical', cue: 'Springy feet save joints' },
    { id: 'elbows_close', question: 'Elbows close to body?', priority: 'important', cue: 'Elbows at sides, not flared' },
    { id: 'wrist_turn', question: 'Turning rope with wrists, not arms?', priority: 'important', cue: 'Wrist rotation = efficiency' },
    { id: 'shoulders_relaxed', question: 'Shoulders relaxed, not hunched?', priority: 'important', cue: 'Drop the shoulders' },
    { id: 'steady_rhythm', question: 'Steady rhythm without tripping?', priority: 'refinement', cue: 'Find your beat' },
    { id: 'minimal_bounce', question: 'Minimal bounce — just enough to clear rope?', priority: 'refinement', cue: 'Low bounce = efficiency' },
  ],
};

export function getFormChecks(exerciseName: string): FormCheck[] {
  return FORM_CHECKS[exerciseName] || [
    { id: 'form_1', question: 'Controlled movement throughout?', priority: 'important', cue: 'Control is king' },
    { id: 'form_2', question: 'Proper breathing?', priority: 'important', cue: 'Breathe with purpose' },
    { id: 'form_3', question: 'Full range of motion?', priority: 'important', cue: 'Don\'t cut corners' },
    { id: 'form_4', question: 'Core braced?', priority: 'critical', cue: 'Brace every rep' },
    { id: 'form_5', question: 'Smooth tempo, not jerky?', priority: 'refinement', cue: 'Rhythm matters' },
  ];
}
